[package]
name = "vrolai"
version = "0.1.0"
edition = "2021"

[features]
default = []
serde = ["dep:serde", "qtty/serde"]

[dependencies]
petgraph = "0.8.3"
qtty = "0.2.2"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"], optional = true }
